### ISSUE TITLE
Undefined class constant 'self::TYPE_CHAR'

### ISSUE THREAD

**Issue by bobolone7** [edgardmessias/yii2-ibm-db2#3] opened 2016-04-21 10:12 UTC
Apache/2.4.6 (CentOS) PHP/7.0.5
Yii Framework/2.0.7

$ris = \common\models\Amministratore::find()->one();
var_dump($ris);
I get that error
I'm connecting via ODBC to an iSeries (I'm already using the same configuration on another app written without yii2)
If I use
$connection = Yii::$app->getDb();
$command = $connection->createCommand("
   SELECT \* FROM GV6_AAA.NNNN");
$result = $command->queryAll();
It works fine

**Comment by jose-acosta-repo** [comment] 2016-04-21 13:43
I am receiving the same error.  Any help would be greatly appreciated

**Comment by bobolone7** [comment] 2016-04-21 14:21
@midcoreadmin in  edgardmessias\db\ibm\db2\Schema add   const TYPE_CHAR =        30;

**Comment by edgardmessias** [comment] 2016-04-21 14:24
The problem is Yii2 version, 2.0.8 is not released.
I make changes to fixe this.

**Comment by edgardmessias** [comment] 2016-04-21 16:16
Fixed in 1.2.1

**Closed as completed** 2016-04-21 16:15 UTC
